// Centralized Mongolian UI strings. Edit here to change wording site-wide.

export const t = {
  nav: {
    home: 'Нүүр',
    vehicles: 'Машинууд',
    contact: 'Холбоо барих',
  },
  common: {
    noImage: 'Зураг байхгүй',
    viewAll: 'Бүгдийг үзэх',
    loading: 'Уншиж байна...',
    back: 'Буцах',
    downPayment: 'Урьдчилгаа',
    price: 'Үнэ',
  },
  status: {
    available: 'Зарагдана',
    sold: 'Зарагдсан',
  },
  home: {
    heroSubtitle: 'Чанартай машины өргөн сонголт',
    browseVehicles: 'Машинууд үзэх',
    forSale: 'Зарагдаж буй машинууд',
    featured: 'Онцлох машинууд',
    latest: 'Шинээр нэмэгдсэн',
    noVehicles: 'Одоогоор машин бүртгэгдээгүй байна.',
    about: 'Бидний тухай',
    workingHours: 'Ажиллах цаг',
    testimonials: 'Үйлчлүүлэгчдийн сэтгэгдэл',
    partners: 'Хамтрагч байгууллагууд',
  },
  vehicles: {
    title: 'Машинууд',
    resultsCount: (n: number) => `${n} машин олдлоо`,
    noResults: 'Хайлтад тохирох машин олдсонгүй.',
    filters: {
      search: 'Хайх',
      searchPlaceholder: 'Брэнд, модель, тайлбар...',
      brand: 'Брэнд',
      year: 'Үйлдвэрлэсэн он',
      minPrice: 'Доод үнэ',
      maxPrice: 'Дээд үнэ',
      sort: 'Эрэмбэлэх',
      apply: 'Шүүх',
      reset: 'Цэвэрлэх',
    },
    sortOptions: {
      newest: 'Шинэ эхэндээ',
      oldest: 'Хуучин эхэндээ',
      price_asc: 'Үнэ: бага → их',
      price_desc: 'Үнэ: их → бага',
      year_desc: 'Он: шинэ → хуучин',
      year_asc: 'Он: хуучин → шинэ',
    },
  },
  detail: {
    specs: 'Үзүүлэлт',
    brand: 'Брэнд',
    model: 'Модель',
    year: 'Үйлдвэрлэсэн он',
    mileage: 'Гүйлт',
    engine: 'Хөдөлгүүр',
    exteriorColor: 'Гадна өнгө',
    interiorColor: 'Дотор өнгө',
    price: 'Үнэ',
    description: 'Тайлбар',
    video: 'Видео',
  },
  loan: {
    title: 'Сарын төлбөрийн тооцоолуур',
    price: 'Машины үнэ',
    downPayment: 'Урьдчилгаа (%)',
    monthlyRate: 'Сарын хүү',
    term: 'Хугацаа',
    selectTerm: 'Хугацаагаа сонгоно уу',
    months: 'сар',
    perMonth: '/сар',
    downAmount: 'Урьдчилгааны дүн',
    loanAmount: 'Зээлийн дүн',
    monthlyPayment: 'Сарын төлбөр',
    minDownNote: 'Хамгийн бага урьдчилгаа',
    disclaimer:
      'Энэхүү тооцоолол нь зөвхөн ойролцоо дүн бөгөөд албан ёсны санал биш.',
  },
  contact: {
    title: 'Холбоо барих',
    phone: 'Утас',
    email: 'И-мэйл',
    address: 'Хаяг',
    viewMap: 'Газрын зураг дээр харах',
    followUs: 'Биднийг дагаарай',
  },
  footer: {
    quickLinks: 'Холбоосууд',
    rights: 'Бүх эрх хуулиар хамгаалагдсан.',
  },
  lead: {
    title: 'Сонирхож байна уу? Холбогдоё',
    titleVehicle: 'Энэ машины талаар лавлах',
    subtitle: 'Нэр, утсаа үлдээгээрэй — бид удахгүй холбогдоно.',
    name: 'Таны нэр',
    phone: 'Утасны дугаар',
    message: 'Нэмэлт мессеж (заавал биш)',
    submit: 'Хүсэлт илгээх',
    submitting: 'Илгээж байна...',
    success: 'Таны хүсэлт амжилттай илгээгдлээ. Бид удахгүй холбогдоно. Баярлалаа!',
    error: 'Илгээхэд алдаа гарлаа. Дахин оролдоно уу.',
    required: 'Нэр болон утсаа бөглөнө үү.',
  },
  admin: {
    login: {
      title: 'Админ нэвтрэх',
      email: 'И-мэйл',
      password: 'Нууц үг',
      submit: 'Нэвтрэх',
      submitting: 'Нэвтэрч байна...',
      error: 'Нэвтрэхэд алдаа гарлаа',
    },
    nav: {
      dashboard: 'Хяналтын самбар',
      vehicles: 'Машинууд',
      leads: 'Хүсэлтүүд',
      settings: 'Тохиргоо',
      help: 'Заавар',
      viewSite: 'Сайт харах',
      logout: 'Гарах',
    },
    dashboard: {
      title: 'Хяналтын самбар',
      total: 'Нийт машин',
      available: 'Зарагдах',
      sold: 'Зарагдсан',
      featured: 'Онцлох',
      addVehicle: 'Машин нэмэх',
      manage: 'Машинууд удирдах',
    },
    leads: {
      title: 'Хүсэлтүүд (лид)',
      empty: 'Одоогоор хүсэлт алга байна.',
      loadError: 'Татахад алдаа гарлаа.',
      colName: 'Нэр',
      colPhone: 'Утас',
      colVehicle: 'Машин',
      colMessage: 'Мессеж',
      colDate: 'Огноо',
      colStatus: 'Төлөв',
      colActions: 'Үйлдэл',
      statusNew: 'Шинэ',
      statusContacted: 'Холбогдсон',
      markContacted: 'Холбогдсон болгох',
      markNew: 'Шинэ болгох',
      delete: 'Устгах',
      confirmDelete: 'Энэ хүсэлтийг устгах уу?',
      filterAll: 'Бүгд',
    },
    vehicles: {
      title: 'Машин удирдах',
      add: 'Машин нэмэх',
      edit: 'Засах',
      delete: 'Устгах',
      confirmDelete: 'Энэ машиныг устгахдаа итгэлтэй байна уу?',
      empty: 'Машин бүртгэгдээгүй байна.',
      loadError: 'Мэдээлэл татахад алдаа гарлаа.',
      filterAll: 'Бүгд',
      colVehicle: 'Машин',
      colYear: 'Он',
      colPrice: 'Үнэ',
      colStatus: 'Төлөв',
      colActions: 'Үйлдэл',
      markSold: 'Зарагдсан',
      markAvailable: 'Зарагдах',
    },
    form: {
      addTitle: 'Шинэ машин нэмэх',
      editTitle: 'Машин засах',
      brand: 'Брэнд',
      model: 'Модель',
      year: 'Үйлдвэрлэсэн он',
      price: 'Үнэ (₮)',
      mileage: 'Гүйлт (км)',
      engine: 'Хөдөлгүүр',
      exteriorColor: 'Гадна өнгө',
      interiorColor: 'Дотор өнгө',
      description: 'Тайлбар',
      images: 'Зургууд',
      video: 'Видео (заавал биш)',
      status: 'Төлөв',
      featured: 'Онцлох машин болгох',
      downPercent: 'Урьдчилгаа (%)',
      downPercentHint: 'Хоосон бол үндсэн тохиргоог ашиглана',
      downPercentPlaceholder: 'Үндсэн тохиргоо',
      save: 'Хадгалах',
      saving: 'Хадгалж байна...',
      cancel: 'Болих',
      requiredError: 'Брэнд, модель, он, үнэ, гүйлтийг бөглөнө үү.',
    },
    upload: {
      selectImages: '+ Зураг нэмэх',
      selectVideo: '+ Видео нэмэх',
      uploading: 'Илгээж байна...',
      hint: 'Олон зураг зэрэг сонгож болно. Эхний зураг нүүр зураг болно.',
      error: 'Илгээхэд алдаа гарлаа. Cloudinary тохиргоог шалгана уу.',
    },
    settings: {
      title: 'Сайтын тохиргоо',
      companyName: 'Компанийн нэр',
      logo: 'Лого',
      banner: 'Нүүр баннер',
      contactSection: 'Холбоо барих',
      phone: 'Утас',
      email: 'И-мэйл',
      address: 'Хаяг',
      socialSection: 'Сошиал хаягууд',
      facebook: 'Facebook',
      instagram: 'Instagram',
      youtube: 'YouTube',
      trustSection: 'Бидний тухай / Итгэл',
      about: 'Бидний тухай (танилцуулга)',
      workingHours: 'Ажиллах цаг (ж: Даваа–Бямба 09:00–19:00)',
      testimonialsSection: 'Үйлчлүүлэгчдийн сэтгэгдэл',
      testimonialName: 'Нэр',
      testimonialText: 'Сэтгэгдэл',
      addTestimonial: '+ Сэтгэгдэл нэмэх',
      remove: 'Устгах',
      partnersSection: 'Хамтрагчийн лого',
      loanSection: 'Зээлийн тохиргоо',
      minDownPercent: 'Хамгийн бага урьдчилгаа (%)',
      monthlyInterestRate: 'Сарын хүү (%)',
      termOptions: 'Хугацааны сонголт (сараар)',
      termOptionsHint: 'Таслалаар тусгаарлана. Жишээ: 12, 24, 36',
      save: 'Хадгалах',
      saving: 'Хадгалж байна...',
      saved: 'Амжилттай хадгалагдлаа.',
    },
  },
};
