// Centralized Mongolian UI strings. Edit here to change wording site-wide.

export const t = {
  nav: {
    home: 'Нүүр',
    vehicles: 'Машинууд',
    contact: 'Холбоо барих',
  },
  common: {
    noImage: 'Зураг байхгүй',
    viewAll: 'Бүгдийг үзэх',
    loading: 'Уншиж байна...',
    back: 'Буцах',
    downPayment: 'Урьдчилгаа',
    price: 'Үнэ',
    added: 'Оруулсан',
    monthly: 'Сарын төлбөр',
    // Short form for the narrow price tiles on cards, where the full
    // "Сарын төлбөр" wraps onto a second line.
    monthlyShort: 'Сард',
    months: 'сар',
    new: 'Шинэ',
  },
  // Primary calls to action. These appear in the sticky mobile bar, on the
  // detail page and in the contact section.
  cta: {
    call: 'Залгах',
    messenger: 'Мессенжер',
    messengerLong: 'Мессенжерээр бичих',
    bookViewing: 'Үзэх цаг авах',
    browse: 'Машинууд үзэх',
  },
  status: {
    available: 'Зарагдана',
    sold: 'Зарагдсан',
  },
  home: {
    heroSubtitle: 'Чанартай машины өргөн сонголт',
    browseVehicles: 'Машинууд үзэх',
    forSale: 'Зарагдаж буй машинууд',
    featured: 'Онцлох машинууд',
    latest: 'Шинээр нэмэгдсэн',
    noVehicles: 'Одоогоор машин бүртгэгдээгүй байна.',
    about: 'Бидний тухай',
    workingHours: 'Ажиллах цаг',
    testimonials: 'Үйлчлүүлэгчдийн сэтгэгдэл',
    partners: 'Хамтрагч байгууллагууд',
    // Live figure — comes straight from the catalog, never hard-coded.
    inventoryCount: (n: number) => `Одоо ${n} машин сонголттой`,
    allVehicles: 'Бүх машин',
    catalog: 'Каталог',
    trust: 'Итгэл',
    sortedNewestNote: 'Шинээр ирсэн нь эхэндээ',
    viewAllCount: (n: number) => `Бүх ${n} машиныг үзэх`,
  },
  vehicles: {
    title: 'Машинууд',
    resultsCount: (n: number) => `${n} машин олдлоо`,
    noResults: 'Хайлтад тохирох машин олдсонгүй.',
    filters: {
      search: 'Хайх',
      searchPlaceholder: 'Брэнд, модель, тайлбар...',
      brand: 'Брэнд',
      year: 'Үйлдвэрлэсэн он',
      minPrice: 'Доод үнэ',
      maxPrice: 'Дээд үнэ',
      sort: 'Эрэмбэлэх',
      apply: 'Шүүх',
      reset: 'Цэвэрлэх',
      open: 'Шүүлт',
    },
    sortOptions: {
      newest: 'Шинэ эхэндээ',
      oldest: 'Хуучин эхэндээ',
      price_asc: 'Үнэ: бага → их',
      price_desc: 'Үнэ: их → бага',
      year_desc: 'Он: шинэ → хуучин',
      year_asc: 'Он: хуучин → шинэ',
    },
  },
  detail: {
    specs: 'Үзүүлэлт',
    brand: 'Брэнд',
    model: 'Модель',
    year: 'Үйлдвэрлэсэн он',
    mileage: 'Гүйлт',
    engine: 'Хөдөлгүүр',
    transmission: 'Хайрцаг',
    steering: 'Хүрд',
    fuel: 'Түлш',
    exteriorColor: 'Гадна өнгө',
    interiorColor: 'Дотор өнгө',
    price: 'Үнэ',
    description: 'Тайлбар',
    video: 'Видео',
    callButton: 'Залгах',
    otherCars: 'Бусад машинууд',
    otherCarsNote: 'Танд тохирох өөр сонголтууд',
    photos: 'Зураг',
    soldTitle: 'Энэ машин зарагдсан байна',
    soldNote: 'Доорх боломжит машинуудаас сонгоно уу.',
  },
  loan: {
    title: 'Сарын төлбөрийн тооцоолуур',
    price: 'Машины үнэ',
    downPayment: 'Урьдчилгаа (%)',
    monthlyRate: 'Сарын хүү',
    term: 'Хугацаа',
    selectTerm: 'Хугацаагаа сонгоно уу',
    months: 'сар',
    perMonth: '/сар',
    downAmount: 'Урьдчилгааны дүн',
    loanAmount: 'Зээлийн дүн',
    monthlyPayment: 'Сарын төлбөр',
    // Equal-payment loan: the same amount every month, start to finish.
    equalNote: 'Сар бүр ижил дүнгээр төлнө',
    totalInterest: 'Нийт хүү',
    downRange: (min: number, max: number) => `${min}–${max}% хооронд сонгоно`,
    betterRateHint: (minDown: number, rate: number) =>
      `Урьдчилгааг ${minDown}% болговол хүү ${rate}% болно`,
    bestRateHint: 'Хамгийн бага хүүтэй',
    rateTableTitle: 'Урьдчилгаанаас хамаарах сарын хүү',
    rateBandFrom: (minDown: number) => `${minDown}%-с дээш`,
    rateBandRange: (from: number, to: number) => `${from}–${to}%`,
    disclaimer:
      'Энэхүү тооцоолол нь зөвхөн ойролцоо дүн бөгөөд албан ёсны санал биш.',
  },
  contact: {
    title: 'Холбоо барих',
    phone: 'Утас',
    email: 'И-мэйл',
    address: 'Хаяг',
    viewMap: 'Газрын зураг дээр харах',
    followUs: 'Биднийг дагаарай',
  },
  footer: {
    quickLinks: 'Холбоосууд',
    rights: 'Бүх эрх хуулиар хамгаалагдсан.',
  },
  lead: {
    title: 'Сонирхож байна уу? Холбогдоё',
    titleVehicle: 'Энэ машины талаар лавлах',
    subtitle: 'Нэр, утсаа үлдээгээрэй — бид удахгүй холбогдоно.',
    name: 'Таны нэр',
    phone: 'Утасны дугаар',
    message: 'Нэмэлт мессеж (заавал биш)',
    submit: 'Хүсэлт илгээх',
    submitting: 'Илгээж байна...',
    success: 'Таны хүсэлт амжилттай илгээгдлээ. Бид удахгүй холбогдоно. Баярлалаа!',
    error: 'Илгээхэд алдаа гарлаа. Дахин оролдоно уу.',
    required: 'Нэр болон утсаа бөглөнө үү.',
  },
  admin: {
    login: {
      title: 'Админ нэвтрэх',
      email: 'И-мэйл',
      password: 'Нууц үг',
      submit: 'Нэвтрэх',
      submitting: 'Нэвтэрч байна...',
      error: 'Нэвтрэхэд алдаа гарлаа',
    },
    nav: {
      dashboard: 'Хяналтын самбар',
      vehicles: 'Машинууд',
      checklist: 'Тооллого',
      windowCards: 'Цонхны хуудас',
      groupMarketing: 'Групп маркетинг',
      leads: 'Хүсэлтүүд',
      settings: 'Тохиргоо',
      help: 'Заавар',
      viewSite: 'Сайт харах',
      logout: 'Гарах',
    },
    // One A4 sheet per car, printed and taped inside its own window.
    windowCards: {
      title: 'Цонхны хуудас',
      subtitle:
        'Машин бүрт нэг A4. Хэвлээд машиныхаа цонхон дээр наана. Шоурүүм дээр ирсэн хүнд хэрэгтэй мэдээлэл л байна.',
      print: 'PDF татах',
      pdfSteps: 'Товч дарахад хэвлэх цонх нээгдэнэ. Тэндээс:',
      pdfStep1: 'Зорилго (Destination) → «PDF болгож хадгалах» сонгох',
      pdfStep2: 'Хадгалах — машин бүр тусдаа хуудастай нэг PDF файл татагдана',
      shape: 'Хэлбэр',
      shapeFull: 'Бүтэн A4',
      shapeTent: 'Майхан (нугалдаг)',
      tentHint:
        'A4-г уртаар нь хоёр хуваан, голоор нь нугалаад машины самбар дээр босгоно. Дээд хагас нь 180° эргүүлсэн тул нугалахад хоёр тал нь зөв уншигдана — нэг тал нь гаднаас, нөгөө тал нь дотор суусан хүнд.',
      withPhoto: 'Зурагтай хэвлэх',
      withPhotoHint: 'Хэрэггүй бол унтраа — бэх их зарцуулна.',
      selectTitle: 'Хэвлэх машинаа сонгох',
      search: 'Дугаар, модель, брэндээр хайх',
      selectHint:
        'Хайгаад тэмдэглэнэ. Хайлтаа цэвэрлэсэн ч тэмдэглэсэн машинууд чинь хэвээрээ үлдэнэ — тэгж нэг нэгээр нь нэмнэ.',
      selectedCount: (n: number) => `${n} сонгосон`,
      willPrintAll: (n: number) => `Бүгд — ${n} хуудас`,
      willPrintSome: (n: number) => `Сонгосон — ${n} хуудас`,
      selectAll: 'Бүгдийг сонгох',
      clearSelection: 'Сонголт цэвэрлэх',
      selectRecent: (days: number) => `Сүүлийн ${days} хоногт нэмэгдсэн`,
      noMatches: 'Хайлтад тохирох машин олдсонгүй.',
      loadError: 'Мэдээлэл татахад алдаа гарлаа.',
      empty: 'Зарагдаж буй машин алга байна.',
      count: (n: number) => `${n} хуудас`,
      price: 'Үнэ',
      down: 'Урьдчилгаа',
      year: 'Он:',
      mileage: 'Гүйлт:',
      monthly: 'Сарын төлбөр',
      months: 'сар',
      noCode: 'Дугааргүй',
    },
    // Printable sheet for walking the lot and reconciling it with the site.
    checklist: {
      title: 'Машины тооллого',
      subtitle:
        'Вэбсайт дээр бүртгэлтэй машинуудыг брэндээр нь жагсаасан хуудас. Хэвлээд талбай дээрээ явж тулгана.',
      intro:
        'Доорх машинууд ВЭБСАЙТ ДЭЭР БАЙГАА. Талбай дээр байгаа боловч энд алга машиныг хамгийн доод хэсэгт бичиж, зургийг нь аваарай.',
      print: 'Хэвлэх / PDF болгож хадгалах',
      printHint:
        'Хэвлэх цонхны "Зорилго" хэсгээс "PDF болгож хадгалах" сонговол файлаар татагдана.',
      includeSold: 'Зарагдсан машинуудыг оруулах',
      blankRows: 'Хоосон мөрийн тоо',
      loadError: 'Мэдээлэл татахад алдаа гарлаа.',
      empty: 'Машин бүртгэгдээгүй байна.',
      printedAt: 'Хэвлэсэн',
      summary: (cars: number, brands: number) => `Нийт ${cars} машин · ${brands} брэнд`,
      brandCount: (n: number) => `${n} машин`,
      colCheck: '✓',
      colCode: 'Дугаар',
      colModel: 'Модель',
      colYear: 'Он',
      colPrice: 'Үнэ (₮)',
      colPhotos: 'Зураг',
      colNote: 'Тэмдэглэл / засвар',
      colBrand: 'Брэнд',
      colPhotoTaken: 'Зураг авав',
      soldTag: 'З/дсан',
      noPhotoWarning: 'Зураггүй',
      missingTitle: 'Жагсаалтад алга — вэбсайт дээр нэмэх машин',
      missingHint: 'Талбай дээр байгаа боловч дээрх жагсаалтад ороогүй машинуудаа бичнэ үү.',
      notesTitle: 'Нэмэлт тэмдэглэл',
    },
    dashboard: {
      title: 'Хяналтын самбар',
      total: 'Нийт машин',
      available: 'Зарагдах',
      sold: 'Зарагдсан',
      featured: 'Онцлох',
      addVehicle: 'Машин нэмэх',
      manage: 'Машинууд удирдах',
    },
    leads: {
      title: 'Хүсэлтүүд (лид)',
      empty: 'Одоогоор хүсэлт алга байна.',
      loadError: 'Татахад алдаа гарлаа.',
      colName: 'Нэр',
      colPhone: 'Утас',
      colVehicle: 'Машин',
      colMessage: 'Мессеж',
      colDate: 'Огноо',
      colStatus: 'Төлөв',
      colActions: 'Үйлдэл',
      statusNew: 'Шинэ',
      statusContacted: 'Холбогдсон',
      markContacted: 'Холбогдсон болгох',
      markNew: 'Шинэ болгох',
      delete: 'Устгах',
      confirmDelete: 'Энэ хүсэлтийг устгах уу?',
      filterAll: 'Бүгд',
    },
    vehicles: {
      title: 'Машин удирдах',
      add: 'Машин нэмэх',
      edit: 'Засах',
      delete: 'Устгах',
      confirmDelete: 'Энэ машиныг устгахдаа итгэлтэй байна уу?',
      empty: 'Машин бүртгэгдээгүй байна.',
      loadError: 'Мэдээлэл татахад алдаа гарлаа.',
      filterAll: 'Бүгд',
      allBrands: 'Бүх брэнд',
      allModels: 'Бүх загвар',
      searchPlaceholder: 'Дугаар, модель, брэндээр хайх…   ( / )',
      searchClear: 'Хайлт цэвэрлэх',
      noSearchResults: (q: string) => `«${q}» хайлтад тохирох машин олдсонгүй.`,
      searchInAll: (n: number) => `Бүх төлөвт ${n} олдлоо — харах`,
      markedSold: (name: string) => `${name} — зарагдсан боллоо.`,
      markedAvailable: (name: string) => `${name} — зарагдана боллоо.`,
      undo: 'Буцаах',
      colVehicle: 'Машин',
      colYear: 'Он',
      colPrice: 'Үнэ',
      colStatus: 'Төлөв',
      colAdded: 'Оруулсан',
      colActions: 'Үйлдэл',
      markSold: 'Зарагдсан',
      markAvailable: 'Зарагдах',
      markSoldSelected: 'Сонгосныг зарагдсан болгох',
      selectedCount: 'сонгосон',
      working: 'Гүйцэтгэж байна...',
      poster: 'Постер',
    },
    // Downloadable social/print poster for a single vehicle.
    poster: {
      title: 'Постер татах',
      subtitle: 'Facebook, Instagram-д тавихад бэлэн PNG',
      format: 'Хэмжээ',
      template: 'Загвар',
      templateLeasing: 'Лизинг',
      templateLeasingHint: 'Үнэ, урьдчилгаа, сарын төлбөр',
      templateOffer: 'Урьдчилгаагүй',
      templateOfferHint: 'Зөвхөн он, гүйлт, үнэ',
      bannerLabel: 'Постер дээрх зарлал',
      bannerDefault: 'Урьдчилгаагүй авах боломжтой',
      bannerHint: 'Хямдрал зарлаж байгаа бол энд бичнэ. Хоосон бол зарлал гарахгүй.',
      badgeOffer: 'Хямдрал',
      formatFeed: '4:5 · Пост',
      formatFeedHint: 'Feed дээр хамгийн том харагдана',
      formatReel: '9:16 · Reel / Story',
      formatReelHint: 'Дэлгэц дүүрэн, босоо',
      badge: 'Лизингээр',
      yearChip: 'Он:',
      mileageChip: 'Гүйлт:',
      priceLabel: 'Үнэ',
      yearLabel: 'Он',
      mileageLabel: 'Гүйлт',
      downLabel: 'Урьдчилгаа',
      monthlyLabel: 'Сарын төлбөр',
      photo: 'Зураг',
      term: 'Хугацаа',
      downPercent: 'Урьдчилгаа (%)',
      // Small print on the poster, under the price tiles.
      termNote: (months: number, rate: number) =>
        `Сарын төлбөрийг ${months} сарын лизингээр, сарын ${rate}% хүүгээр бодсон. Сар бүр ижил дүнгээр төлнө.`,
      phone: 'Утас',
      address: 'Хаяг',
      website: 'Вэб хаяг',
      contactHint:
        'Утас нь Тохиргооноос, хаяг нь постерийн үндсэн хаягаас орж ирнэ. Энд засвал зөвхөн постерт нөлөөлнө (админаас гарах хүртэл хадгалагдана).',
      // Explains how the monthly figure was reached.
      calcNote: (rate: number, down: number, interest: string) =>
        `Урьдчилгаа ${down}% → сарын хүү ${rate}%. Тэнцүү төлөлтөөр бодсон, нийт хүү ${interest}.`,
      roundingNote: 'Дүнг ойролцоогоор 1,000₮ хүртэл бүхэлчилсэн.',
      noPhoto: 'Энэ машинд зураг алга — постер зураггүй гарна.',
      download: 'PNG татах',
      preparing: 'Бэлдэж байна...',
      close: 'Хаах',
      error: 'Постер үүсгэхэд алдаа гарлаа. Дахин оролдоно уу.',
    },
    form: {
      addTitle: 'Шинэ машин нэмэх',
      editTitle: 'Машин засах',
      brand: 'Брэнд',
      model: 'Модель',
      year: 'Үйлдвэрлэсэн он',
      price: 'Үнэ (₮)',
      mileage: 'Гүйлт (км)',
      engine: 'Хөдөлгүүр',
      transmission: 'Хайрцаг',
      steering: 'Хүрд',
      fuel: 'Түлш',
      selectOption: '— Сонгох —',
      exteriorColor: 'Гадна өнгө',
      interiorColor: 'Дотор өнгө',
      description: 'Тайлбар',
      images: 'Зургууд',
      video: 'Видео (заавал биш)',
      status: 'Төлөв',
      featured: 'Онцлох машин болгох',
      downPercent: 'Урьдчилгаа (%)',
      downPercentHint: 'Хоосон бол үндсэн тохиргоог ашиглана',
      downPercentPlaceholder: 'Үндсэн тохиргоо',
      save: 'Хадгалах',
      saving: 'Хадгалж байна...',
      cancel: 'Болих',
      requiredError: 'Брэнд, модель, он, үнэ, гүйлтийг бөглөнө үү.',
    },
    // Ready-made posts for Facebook groups: the car's photos, clean, plus
    // the text that goes with them.
    groupMarketing: {
      title: 'Групп маркетинг',
      subtitle:
        'Групп дээр тавих зар. Машинаа сонгоод зургийг нь татаад, бэлэн текстийг хуулж авна.',
      phone: 'Зар дээр гарах утас',
      phoneHint: 'Энэ хөтөч дээр хадгалагдана. Сайтын үндсэн дугаараас тусдаа.',
      withPrice: 'Үнийг зар дээр бичих',
      branded: 'Усан тэмдэг, хүрээтэй зураг татах',
      brandedHint: 'Сайт дээр харагддаг хувилбар — лого, утасны чип, улаан хүрээтэй.',
      plainHint: 'Лого, хүрээ, усан тэмдэггүй эх зураг татагдана.',
      selectTitle: 'Машин сонгох',
      search: 'Арлын 4 орон эсвэл загвараар хайх',
      selectRecent: (days: number) => `Сүүлийн ${days} хоногт нэмэгдсэн`,
      clearSelection: 'Сонголтыг цэвэрлэх',
      noMatches: 'Тохирох машин олдсонгүй',
      selectHint:
        'Хайгаад чагтална. Хайлтаа цэвэрлэсэн ч чагтлагдсан машин хэвээр үлдэнэ.',
      chosenCount: (n: number) => `${n} машин сонгогдсон`,
      empty: 'Дээрээс машинаа сонгоход зураг болон бэлэн текст нь энд гарч ирнэ.',
      loadError: 'Машины жагсаалтыг уншиж чадсангүй.',
      photos: (n: number) => `Зураг (${n})`,
      downloadAll: 'Бүх зургийг татах',
      downloading: 'Татаж байна...',
      downloadFailed: (n: number) =>
        `${n} зураг татагдсангүй. Зураг дээр нь дарж гараар хадгална уу.`,
      openImage: 'Шинэ цонхонд нээх',
      description: 'Зарын текст',
      copy: 'Хуулах',
      copied: 'Хуулагдлаа ✓',
      copyFailed: 'Хуулж чадсангүй. Текстээ сонгоод Ctrl+C дарна уу.',
      reset: 'Буцаах',
    },
    upload: {
      selectImages: '+ Зураг нэмэх',
      selectVideo: '+ Видео нэмэх',
      uploading: 'Илгээж байна...',
      hint: 'Олон зураг зэрэг сонгож болно. Эхний зураг нүүр зураг болно.',
      error: 'Илгээхэд алдаа гарлаа.',
      tooLarge: (mb: string, maxMb: number) =>
        `Файл хэт том байна (${mb} MB). ${maxMb} MB-аас бага байх ёстой — жижигрүүлээд дахин оруулна уу.`,
      serverTooLarge:
        'Файл хэт том байгаа тул сервер хүлээж авсангүй. Жижигрүүлээд дахин оруулна уу.',
    },
    settings: {
      title: 'Сайтын тохиргоо',
      companyName: 'Компанийн нэр',
      logo: 'Лого',
      banner: 'Нүүр баннер',
      contactSection: 'Холбоо барих',
      phone: 'Утас',
      email: 'И-мэйл',
      address: 'Хаяг',
      mapUrl: 'Google Maps линк',
      mapUrlHint: 'Google Maps дээрх байршлынхаа "Share/Хуваалцах" линкийг буулгана.',
      socialSection: 'Сошиал хаягууд',
      facebook: 'Facebook',
      instagram: 'Instagram',
      youtube: 'YouTube',
      trustSection: 'Бидний тухай / Итгэл',
      about: 'Бидний тухай (танилцуулга)',
      workingHours: 'Ажиллах цаг (ж: Даваа–Бямба 09:00–19:00)',
      testimonialsSection: 'Үйлчлүүлэгчдийн сэтгэгдэл',
      testimonialName: 'Нэр',
      testimonialText: 'Сэтгэгдэл',
      addTestimonial: '+ Сэтгэгдэл нэмэх',
      remove: 'Устгах',
      partnersSection: 'Хамтрагчийн лого',
      loanSection: 'Зээлийн тохиргоо',
      minDownPercent: 'Үндсэн урьдчилгаа (%)',
      monthlyInterestRate: 'Сарын хүү (урьдчилгаанаас хамаарна)',
      interestBandsHint: 'Хүүг lib/loan.ts доторх INTEREST_BANDS хүснэгтээс өөрчилнө.',
      termOptions: 'Хугацааны сонголт (сараар)',
      termOptionsHint: 'Таслалаар тусгаарлана. Жишээ: 12, 24, 36',
      imagesSection: 'Зургийн боловсруулалт',
      imagesHint:
        'Шинээр оруулах машины зурагт автоматаар хэрэгжинэ: жижигрүүлж, шахаж, лого + утасны дугаар + хүрээ дарна. Хуучин зургуудад нөлөөлөхгүй.',
      maxWidth: 'Хамгийн их өргөн (px)',
      watermarkEnabled: 'Watermark идэвхжүүлэх',
      watermarkText: 'Зураг дээр бичих текст',
      watermarkTextHint:
        'Хоосон бол холбоо барих утасны дугаарыг ашиглана. Хэмжээ нь зураг бүрийн өргөнд тохируулан автоматаар тодорхойлогдоно.',
      watermarkPosition: 'Логоны байрлал',
      watermarkFont: 'Үсгийн фонт',
      watermarkColor: 'Хүрээ ба текстийн өнгө',
      watermarkStyle: 'Тамганы загвар',
      watermarkStyleClassic: 'Хуучин',
      watermarkStyleClassicHint: 'Лого нэг буланд, утасны хаяг нөгөөд, улаан хүрээтэй.',
      watermarkStyleMarks: 'Шинэ брэнд',
      watermarkStyleMarksHint:
        'Вэб хаяг дээд дунд, лого зүүн доод, утас баруун доод. Хүрээгүй.',
      marksTitle: 'Брэндийн тамганууд',
      marksHint:
        'Гурвууланг нь оруулна. Дэвсгэргүй PNG байх ёстой. Хоосон орхивол тэр тамга гарахгүй, гурвуулаа хоосон бол хуучин загвараар дарагдана.',
      websiteMark: 'Вэб хаягийн тамга (дээд дунд)',
      logoMark: 'Логоны тамга (зүүн доод)',
      phoneMark: 'Утасны тамга (баруун доод)',
      posBottomRight: 'Баруун доод',
      posBottomLeft: 'Зүүн доод',
      posTopRight: 'Баруун дээд',
      posTopLeft: 'Зүүн дээд',
      posCenter: 'Төв',
      save: 'Хадгалах',
      saving: 'Хадгалж байна...',
      saved: 'Амжилттай хадгалагдлаа.',
    },
  },
};
